/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
  basics: [
    'basics',
    'basics/quick-start',
    'basics/installation',
    'basics/updates',
    'basics/creating-post-types',
    'basics/creating-taxonomies',
    'basics/creating-meta-boxes',
    'basics/field-settings',
    'basics/displaying-fields',
    'basics/shortcode',
    {
      type: 'category',
      label: 'Online Tools',
      link: {
        type: 'generated-index',
      },
      items: [
        'basics/online-tools/post-type-generator',
        'basics/online-tools/taxonomy-generator',
        'basics/online-tools/online-generator',
      ],
    },
    {
      type: 'category',
      label: 'Compatibility',
      link: {
        type: 'generated-index',
      },
      items: [
        'basics/compatibility/plugins',
        'basics/compatibility/themes',
        'basics/compatibility/hostings',
      ],
    },
  ],

  advanced: [
    'advanced',
    'advanced/cloning-fields',
    'advanced/validation',
    'advanced/sanitization',
    'advanced/custom-attributes',
    'advanced/integration',
    'advanced/database',
    'advanced/custom-field-type',
    'advanced/html5-input-types',
    'advanced/composer',
  ],

  fields: [
    'fields',
    {
      type: 'autogenerated',
      dirName: 'fields',
    },
  ],

  extensions: [
    'extensions',
    {
      type: 'autogenerated',
      dirName: 'extensions',
    },
  ],

  references: [
    'references',
    {
      type: 'autogenerated',
      dirName: 'references',
    },
  ],

  tutorials: [
    'tutorials',
    {
      type: 'autogenerated',
      dirName: 'tutorials',
    },
  ],
};

module.exports = sidebars;
