/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
	sidebar: [
		{
			type: 'category',
			label: 'Getting Started',
			link: {
				type: 'generated-index',
			},
			items: [
				'why-meta-box',
				'installation',
				'creating-post-types',
				'creating-taxonomies',
				'creating-meta-boxes',
				{
					type: 'category',
					label: 'Displaying fields',
					link: {
						type: 'doc',
						id: 'displaying-fields',
					},
					items: [
						{
							type: 'doc',
							id: 'display-fields-with-views',
							label: 'With views',
						},
						{
							type: 'doc',
							id: 'display-fields-with-code',
							label: 'With code',
						},
						{
							type: 'doc',
							id: 'display-fields-with-beaver-builder',
							label: 'With Beaver Builder',
						},
						{
							type: 'doc',
							id: 'display-fields-with-elementor',
							label: 'With Elementor',
						},
					],
				}
			],
		},
		{
			type: 'category',
			label: 'Field types',
			link: {
				type: 'generated-index',
				slug: 'category/fields',
			},
			items: [
				{
					type: 'autogenerated',
					dirName: 'fields',
				}
			],
		},
		{
			type: 'category',
			label: 'Extensions',
			link: {
				type: 'generated-index',
			},
			items: [
				{
					type: 'autogenerated',
					dirName: 'extensions',
				}
			],
		},
		{
			type: 'category',
			label: 'Advanced',
			link: {
				type: 'generated-index',
			},
			items: [
				'shortcode',
				'cloning-fields',
				'validation',
				'sanitization',
				'custom-attributes',
				'integration',
				'database',
				'custom-field-type',
				'html5-input-types',
				'composer',
				'actions',
				'filters',
				{
					Functions: [
						'rwmb-meta',
						'rwmb-set-meta',
						'rwmb-get-value',
						'rwmb-the-value',
						'rwmb-get-object-fields',
						'rwmb-get-field-settings',
						'rwmb-get-registry',
					],
				}
			],
		},
		{
			type: 'category',
			label: 'Others',
			link: {
				type: 'generated-index',
			},
			items: [
				'updates',
				'support-policy',
				'compatibility',
			],
		},
	],
};

module.exports = sidebars;
